name: jira-client
version: 0.1
author: Tristan Cacqueray
maintainer: tdecacqu@redhat.com
synopsis: A Jira client library
description: |
    jira-client is a library to interface with https://www.atlassian.com/software/jira.
    .
    Use this library to query and post to Jira REST API.
    .
github: ButlerOS/haskell-jira-client
language: GHC2021
category: Development
extra-source-files:
  - test/data/*

ghc-options:
  - -Wall
  - -fwarn-incomplete-uni-patterns
  - -Wno-partial-type-signatures
  - -fwrite-ide-info
  - -Wno-missing-methods

default-extensions:
  - OverloadedStrings
  - NamedFieldPuns
  - ImportQualifiedPost
  - LambdaCase
  - ViewPatterns
  - MultiWayIf
  - QuasiQuotes
  - DeriveGeneric
  - DerivingVia
  - GeneralizedNewtypeDeriving
  - DuplicateRecordFields
  - RecordWildCards
  - OverloadedStrings
  - OverloadedRecordDot
  - TemplateHaskell
  - DataKinds
  - DeriveAnyClass
  - TypeFamilies
  - BlockArguments
  - OverloadedLabels
  - DerivingStrategies
  - PartialTypeSignatures

dependencies:
  - base < 5
  - aeson
  - lens
  - lens-aeson
  - http-client
  - bytestring
  - text
  - time
  - witch

library:
  source-dirs: src

tests:
  jira-spec:
    main: Spec.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-T
    source-dirs: test
    dependencies:
      - jira-client
      - tasty
      - tasty-hunit
      - wai
      - http-types
      - http-mock
