name: release
on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    outputs:
      md2jira_version: ${{ env.MD2JIRA_VERSION }}
    steps:
      - uses: actions/checkout@v3

      - name: Get the release version from the tag
        shell: bash
        run: |
          echo "MD2JIRA_VERSION=$GITHUB_REF_NAME" >> $GITHUB_ENV
          echo "version is: ${{ env.MD2JIRA_VERSION }}"

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ env.MD2JIRA_VERSION }}

  create-container-release:
    name: create-container-release
    needs: ['create-release']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Push Image
        run: nix run ".#publish-container-release"
        env:
          GH_USERNAME: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
